<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dls210" ignored="0" name="Teste" tests="4" failures="1" timestamp="16 jul 2018 23:27:11 GMT" time="0.107" errors="0">
  <testcase name="String" time="0.042" classname="testclasses.TestNGAssert"/>
  <testcase name="array" time="0.001" classname="testclasses.TestNGAssert"/>
  <testcase name="testeSum" time="0.002" classname="testclasses.TestNGAssert"/>
  <testcase name="testSum" time="0.007" classname="testclasses.TestNGSoftAssert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [2] but found [3]
at testclasses.TestNGSoftAssert.testSum(TestNGSoftAssert.java:21)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSum -->
</testsuite> <!-- Teste -->
